### ISSUE TITLE
Annotation in progress: domain error: argument not in valid range 

### ISSUE THREAD

**Issue by georgiesamaha** [lgmgeo/AnnotSV#148]
Hi @lgmgeo, 

Firstly, thanks for AnnotSV, its such a great tool. 

I've been running the command line tool on some multi-caller VCFs and came across an error that I've had no luck in resolving. My command is: 

```
/data/ALS_scripts/AnnotSV/bin/AnnotSV \
    -SVinputFile ${vcf} \
    -annotationsDir /data/tools/AnnotSV/share/AnnotSV \
    -bedtools /data/tools/bedtools \
    -bcftools /data/tools/bcftools-1.16/bcftools \
    -annotationMode full \
    -genomeBuild GRCh38 \
    -includeCI 1 \
    -overwrite 1 \
    -outputFile ./sample_AnnotSV.tsv
```

For most samples this works perfectly, but for 2 samples it fails at the annotation in progress stage. Here is the stdout: 
```
AnnotSV 3.2

Copyright (C) 2017-2022 GEOFFROY Veronique

Please feel free to contact me for any suggestions or bug reports
email: veronique.geoffroy@inserm.fr

Tcl/Tk version: 8.6

Application name used (defined with the "ANNOTSV" environment variable):
/data/tools/AnnotSV/


...downloading the configuration data (December 21 2022 - 06:49)
        ...configuration data by default
        ...configuration data from /data/tools/AnnotSV/etc/AnnotSV/configfile
        ...configuration data given in arguments
        ...checking all these configuration data

...checking the annotation data sources

WARNING: No GeneHancer annotations available.
(Please, see in the README file how to add these annotations. Users need to contact the GeneCards team.)


...listing arguments
        ******************************************
        AnnotSV has been run with these arguments:
        ******************************************
        -REreport 0
        -REselect1 1
        -REselect2 1
        -SVinputFile /data/SV_validation/sample.vcf
        -SVinputInfo 1
        -SVminSize 50
        -annotationMode full
        -annotationsDir /data/tools/AnnotSV/share/AnnotSV
        -bcftools /data/tools/bcftools-1.16/bcftools
        -bedtools /data/tools/bedtools
        -benignAF 0.01
        -candidateGenesFiltering 0
        -cytoband 1
        -genomeBuild GRCh38
        -includeCI 1
        -metrics us
        -miRNAann 1
        -minTotalNumber 500
        -organism Human
        -outputDir .
        -outputFile sample_AnnotSV.tsv
        -overlap 100
        -overwrite 1
        -promoterSize 500
        -rankFiltering 1 2 3 4 5 NA
        -reciprocal 0
        -samplesidBEDcol -1
        -snvIndelPASS 0
        -svtBEDcol -1
        -tx RefSeq
        -vcf 0
        ******************************************

...searching for SV overlaps with a gene or a regulatory elements
        ...18218 genes overlapped with an SV
        ...22852 genes regulated by a regulatory element which is overlapped with an SV

...listing of the annotations to be realized (December 21 2022 - 06:52)
        ...CytoBand annotation
        ...Genes annotation
                ...RefSeq annotation
        ...Regulatory elements annotations
                ...Promoter annotations
                ...EnhancerAtlas annotations
        ...Annotations with pathogenic genes or genomic regions
                ...dbVar annotation
                ...ClinVar annotation
                ...ClinGen annotation
        ...Annotations with pathogenic snv/indel
        ...Annotations with benign genes or genomic regions
                ...gnomAD annotation
                ...ClinVar annotation
                ...ClinGen annotation
                ...DGV annotation
                ...DDD annotation
                ...1000g annotation
                ...Ira M. Hall's lab annotation
                ...Children’s Mercy Research Institute
        ...Annotations with features overlapped with the SV (100 %)
                ...TAD annotation
        ...Annotations with features sharing any overlap with the SV
        ...Breakpoints annotations
                ...GC content annotation
                ...Repeat annotation
                ...Gap annotation
                ...Segmental duplication annotation
                ...ENCODE blacklist annotation
        ...Gene-based annotations
                ...20220617_ACMG.tsv
                (78 gene identifiers and 1 annotations columns: ACMG)
                ...20220906_ClinGenAnnotations.tsv
                (1480 gene identifiers and 2 annotations columns: HI, TS)
                ...20200713_HI.tsv.gz
                (19124 gene identifiers and 1 annotations columns: DDD_HI_percent)
                ...20191219_ExAC.CNV-Zscore.annotations.tsv.gz
                (15673 gene identifiers and 3 annotations columns: ExAC_delZ, ExAC_dupZ, ExAC_cnvZ)
                ...20201023_GeneIntolerance-Zscore.annotations.tsv.gz
                (18241 gene identifiers and 2 annotations columns: ExAC_synZ, ExAC_misZ)
                ...20220902_GenCC.tsv
                (4615 gene identifiers and 4 annotations columns: GenCC_disease, GenCC_moi, GenCC_classification, GenCC_pmid)
                ...20220905_OMIM-1-annotations.tsv.gz
                (16250 gene identifiers and 1 annotations columns: OMIM_ID)
                ...20220905_OMIM-2-annotations.tsv.gz
                (16250 gene identifiers and 2 annotations columns: OMIM_phenotype, OMIM_inheritance)
                ...20220905_morbid.tsv.gz
                (12998 gene identifiers and 1 annotations columns: OMIM_morbid)
                ...20220905_morbidCandidate.tsv.gz
                (3467 gene identifiers and 1 annotations columns: OMIM_morbid_candidate)
                ...20201106_gnomAD.LOEUF.pLI.annotations.tsv.gz
                (19451 gene identifiers and 3 annotations columns: LOEUF_bin, GnomAD_pLI, ExAC_pLI)

...annotation in progress (December 21 2022 - 06:52)
domain error: argument not in valid range
    while executing
"expr {($po_end-$po_start)*100.0/($endP-$startP)}"
    (procedure "poPathogenicSVannotation" line 59)
    invoked from within
"poPathogenicSVannotation $SVchrom $SVleft $SVright"
    (procedure "OrganizeAnnotation" line 767)
    invoked from within
"OrganizeAnnotation"
    (file "/data/ALS_scripts/AnnotSV/bin/AnnotSV" line 282)
```

Given AnnotSV works for all my other samples and the web-based version also fails on this sample (just outputs an empty .tsv) but not others I know this is a problem with my VCF. All the VCFs (successful and unsuccessful) have been processed with the same workflow. Do you know why this might be happening and how I can resolve it? 

Thanks very much for your help :)

**Comment by lgmgeo** [comment]
Hi @georgiesamaha,

Thank you for this report. I will have a look at this bug and come back to you asap.

Véronique

**Comment by lgmgeo** [comment]
Ok, I found an example with the same bug.
Actually, some dbVar SV have the same start and end locations:
https://www.ncbi.nlm.nih.gov/dbvar/?term=nssv17171884
I need to embed this in the AnnotSV code.

**Comment by lgmgeo** [comment]
It is to notice that 42 CNV from dbVar are surprisingly described with the same start and end location:
```10      2187182 2187182                 dbVar:nssv17968623      10:2187182-2187182
10      14750351        14750351                        dbVar:nssv17975750      10:14750351-14750351
10      74987633        74987633                        dbVar:nssv17975236      10:74987633-74987633
11      196401  196401                  dbVar:nssv17975552      11:196401-196401
11      27095138        27095138                        dbVar:nssv17975903      11:27095138-27095138
12      22632423        22632423                        dbVar:nssv17976031      12:22632423-22632423
12      29773582        29773582                        dbVar:nssv17976032      12:29773582-29773582
12      60618816        60618816                        dbVar:nssv17976033      12:60618816-60618816
13      32890470        32890470                        dbVar:nssv15119415      13:32890470-32890470
13      49242720        49242720                        dbVar:nssv17975594      13:49242720-49242720
14      31269856        31269856                        dbVar:nssv17975889      14:31269856-31269856
15      5185    5185                    dbVar:nssv17976462      15:5185-5185
15      57248506        57248506                        dbVar:nssv17975423      15:57248506-57248506
18      10362350        10362350                        dbVar:nssv17975553      18:10362350-10362350
18      65346546        65346546                        dbVar:nssv17975931      18:65346546-65346546
19      29247464        29247464                        dbVar:nssv17975396      19:29247464-29247464
2       54294943        54294943                        dbVar:nssv17975580      2:54294943-54294943
2       167032703       167032703                       dbVar:nssv17975879      2:167032703-167032703
20      5393968 5393968                 dbVar:nssv17968633      20:5393968-5393968
21      35742772        35742772                        dbVar:nssv17171511      21:35742772-35742772
3       10094065        10094065                        dbVar:nssv17172411      3:10094065-10094065
3       10106407        10106407                        dbVar:nssv17172628      3:10106407-10106407
3       149332307       149332307                       dbVar:nssv17975767      3:149332307-149332307
4       173991710       173991710                       dbVar:nssv17975441      4:173991710-173991710
5       84762134        84762134                        dbVar:nssv17975343      5:84762134-84762134
5       92616397        92616397                        dbVar:nssv17975614      5:92616397-92616397
5       94502031        94502031                        dbVar:nssv17975342      5:94502031-94502031
5       153852297       153852297                       dbVar:nssv17975615      5:153852297-153852297
6       56330866        56330866                        dbVar:nssv17171884      6:56330866-56330866
6       66157097        66157097                        dbVar:nssv17975717      6:66157097-66157097
6       70100804        70100804                        dbVar:nssv17968632      6:70100804-70100804
6       80345233        80345233                        dbVar:nssv17975918      6:80345233-80345233
6       82288681        82288681                        dbVar:nssv17975919      6:82288681-82288681
6       93909993        93909993                        dbVar:nssv17975820      6:93909993-93909993
6       116841827       116841827                       dbVar:nssv17975385      6:116841827-116841827
6       140836347       140836347                       dbVar:nssv17976004      6:140836347-140836347
6       144917096       144917096                       dbVar:nssv17968606      6:144917096-144917096
7       6580928 6580928                 dbVar:nssv17975600      7:6580928-6580928
7       15126335        15126335                        dbVar:nssv17975601      7:15126335-15126335
7       16588050        16588050                        dbVar:nssv17975602      7:16588050-16588050
8       65187602        65187602                        dbVar:nssv17968622      8:65187602-65187602
X       9728757 9728757                 dbVar:nssv15119749      X:9728757-9728757
```

**Comment by lgmgeo** [comment]
OK, I just fixed this bug in the v3.2.1.
Can you please install this v3.2.1 and check if everything works?
Thank you for your help.

**Comment by georgiesamaha** [comment]
Thank you so much @lgmgeo!! I installed and ran v3.2.1 with same command, same sample and it ran to completion without error.

**Comment by Qijie0615** [comment]
I'm using version 3.3.1, and  I still have the same error report.
...annotation in progress (October 24 2023 - 13:00)
domain error: argument not in valid range
    while executing
"expr {($po_end-$po_start)*100.0/($endP-$startP)}"
    (procedure "poPathogenicSVannotation" line 64)
    invoked from within
"poPathogenicSVannotation $SVchrom $SVleft $SVright"
    (procedure "OrganizeAnnotation" line 754)
    invoked from within
"OrganizeAnnotation"
